version: '3.7'
services:
  authorization-service:
    image: jboss/keycloak
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: keycloak-db
      DB_DATABASE: keycloak
      DB_USER: postgres
      DB_SCHEMA: public
      DB_PASSWORD: postgres
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: Pa55w0rd
      PROXY_ADDRESS_FORWARDING: 'true'
      TZ: Europe/Warsaw
    ports:
      - 9000:8080
    configs:
      - source: keycloak-profile-settings
        target: /opt/jboss/keycloak/standalone/configuration/profile.properties

  kong-db:
    image: postgres
    volumes:
      - postgres_data_kong:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_DB=kong
      - POSTGRES_PASSWORD=kong

  keycloak-db:
    image: postgres
    volumes:
      - postgres_data_keycloak:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=keycloak
      - POSTGRES_PASSWORD=postgres

  kong-migration:
    image: kong:last
    depends_on:
      - postgres-db
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-db
      - KONG_PG_PASSWORD=kong
    command: sh -c "kong migrations bootstrap && touch migrations_run && sleep 30"
    healthcheck:
      test: "if [[ -f migrations_run ]] ; then exit 0; else exit 1; fi"
      interval: 10s
      timeout: 5s
      retries: 5

  kong:
    image: kong:last
    depends_on:
      - kong-migration
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-db
      - KONG_PG_PASSWORD=kong
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
    ports:
      - 8000:8000
      - 8001:8001

  mongo:
    image: mongo
    volumes:
      - mongo_data:/data/db
    ports:
      - 27017:27017

  konga:
    image: pantsel/konga
    depends_on:
      - kong
      - mongo
    ports:
      - 1337:1337
    environment:
      - DB_ADAPTER=mongo
      - DB_HOST=mongo
      - DB_DATABASE=konga

configs:
  keycloak-profile-settings:
    file: ./profile.properties

volumes:
  postgres_data_keycloak:
  postgres_data_kong:
  mongo_data:
